def raise_exception():
    return 1 / 0